import express from "express";
import db from "./config/db.js";
import dotenv from "dotenv";
import blogRoutes from "./routes/blog.route.js";
const app = express();
db();
dotenv.config();
const PORT = process.env.PORT || 3000;
app.use(express.json());
app.use("/api/v1", blogRoutes);
app.listen(PORT, () => console.log(`App Started on https://localhost:${PORT} `));
